external-dns:
  serviceAccount:
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::278264368218:role/central-external-dns
  policy: upsert-only
  txtOwnerId: central
  extraArgs:
    - --aws-zone-type=public
