clusterName: central

karpenter:
  replicas: 1
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::278264368218:role/central-karpenter-controller
  clusterName: central
  clusterEndpoint: "https://36A1C04A4707285598F8535E3C3AD5B4.gr7.us-east-1.eks.amazonaws.com"
  aws:
    defaultInstanceProfile: KarpenterNodeInstanceProfile-central

provisionerList:
  default:
    labels:
      nodeType: default
      nodeSubnet: private
    requirements:
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: [ "t3.large" ]
      - key: "kubernetes.io/arch"
        operator: In
        values: [ "amd64" ]
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: [ "us-east-1a", "us-east-1b", "ap-east-1c" ]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: [ "on-demand", "spot" ]
  vault-worker:
    labels:
      nodeType: vault-worker
      nodeSubnet: private
    requirements:
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: [ "t3.micro" ]
      - key: "kubernetes.io/arch"
        operator: In
        values: [ "amd64" ]
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: [ "us-east-1a", "us-east-1b", "us-east-1c" ]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: [ "on-demand" ]
    taints:
      - key: workerType
        value: vault
        effect: NoSchedule
